name: publish
on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.HUB_USERNAME }}
  DOCKER_IMAGE: sply
  DOCKER_IMAGE_TAG: "http"

jobs:
  docker:
    env:
      PLATFORMS: linux/amd64,linux/arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ env.PLATFORMS }}
          context: .
          push: true
          file: ./build/Dockerfile
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
